networks:
  chat:
    driver: bridge

services:

  # service for the backend api
  backend:
    container_name: "chat-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - database-server
    networks:
      - chat

  # service for the frontend
  frontend:
    container_name: "chat-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - chat
  
  # service for mysql database server
  database-server:
    container_name: "chat-database-server"
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - chat
  
  # service for phpmyadmin database management
  database-admin-panel:
    container_name: "chat-database-admin-panel"
    image: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment: 
      PMA_HOST: database-server
      PMA_PASSWORD: ""
      PMA_USER: "root"
    depends_on: 
      - database-server
    networks:
      - chat

volumes:
  dbdata: